# Multi-agent team configuration using Claude Code Stream backend
# Demonstrates multi-agent coordination with claude-code-sdk capabilities

agents:
  - id: "claude_developer"
    backend:
      type: "claude_code_stream"
      model: "claude-sonnet-4-20250514"
      max_turns: 3
      system_prompt: "You are a software developer powered by Claude Code. You excel at reading, writing, and editing code. Use file operations, code execution, and debugging tools to solve programming challenges. Focus on clean, maintainable code solutions."
      allowed_tools:
        - "Read"
        - "Write" 
        - "Edit"
        - "MultiEdit"
        - "Bash"
        - "Grep"
        - "Glob"
        - "LS"
        - "mcp__ide__getDiagnostics"
        - "mcp__ide__executeCode"
        
  - id: "claude_researcher"
    backend:
      type: "claude_code_stream" 
      model: "claude-3-5-sonnet-20241022"
      max_turns: 3
      system_prompt: "You are a research specialist powered by Claude Code. You excel at finding information, analyzing web content, and synthesizing research findings. Use web search and content fetching tools to gather comprehensive information."
      allowed_tools:
        - "Read"
        - "Write"
        - "WebSearch"
        - "WebFetch"
        - "Grep"
        - "Glob"
        - "LS"
        
  - id: "claude_coordinator"
    backend:
      type: "claude_code_stream"
      model: "claude-3-5-haiku-20241022"
      max_turns: 3
      system_prompt: "You are a project coordinator powered by Claude Code. You excel at organizing tasks, managing workflows, and synthesizing team outputs. Use task management tools and file operations to coordinate collaborative work."
      allowed_tools:
        - "Read"
        - "Write"
        - "Edit"
        - "TodoWrite"
        - "Bash"
        - "LS"

# UI Configuration  
ui:
  type: "rich_terminal"
  show_agent_thinking: true
  show_coordination: true
  
# Multi-agent orchestration settings
orchestration:
  max_coordination_rounds: 5
  timeout_seconds: 600
  voting_threshold: 0.6  # 60% agreement needed for consensus
  
# Session configuration
session:
  save_conversation: true
  session_file: "claude_code_team_session.json"