agent:
  id: "claude_code_twitter_enescinar"
  backend:
    type: "claude_code"
    cwd: "claude_code_twitter_enescinar_workspace"
    permission_mode: "bypassPermissions"
    
    # Twitter MCP server - using EnesCinr/twitter-mcp
    mcp_servers:
      twitter:
        type: "stdio"
        command: "npx"
        args: ["-y", "@enescinar/twitter-mcp"]
        env:
          # You need to get these from Twitter Developer Portal: https://developer.twitter.com/
          # Required credentials:
          API_KEY: "POfjVW8gvZcDN8nVEtL61qoV8"
          API_SECRET_KEY: "34rpnLlopzniH9LpnGLDuOSdUg4BnqP9bLdGEClWyJGIvWpeMr"
          ACCESS_TOKEN: "826811862662541312-vTO5V7QaL5scXqI44K2Br2zrLhlG2hl"
          ACCESS_TOKEN_SECRET: "7421nyljz8nI4zU6x4KY0dQ9DfNp0SXnLrMEfLjImyVZB"
        
    allowed_tools:
      - "Read"
      - "Write"
      - "Bash"
      - "LS"
      - "WebSearch"
      # MCP tools will be auto-discovered from the server
      
  system_message: |
    You are using the EnesCinr Twitter MCP integration with Claude Code.
    
    You have access to Twitter MCP server tools for posting and searching tweets.
    
    Available MCP tools (these will be prefixed with mcp__twitter__):
    - post_tweet: Post a new tweet to Twitter
    - search_tweets: Search for tweets based on query

ui:
  display_type: "simple"
  logging_enabled: true