# Test configuration to verify backend type inference
# This config doesn't specify backend type - it should be inferred from model

agents:
  - id: "openai_agent"
    backend:
      # No type specified - should infer "openai" from model
      model: "gpt-4o-mini"
      enable_web_search: true
    system_message: "You are an OpenAI assistant."
    
  - id: "gpt_agent"
    backend:
      # No type specified - should infer "claude" from model
      model: "gpt-4o-mini"
      enable_web_search: true
    system_message: "You are another OpenAI assistant."
    
  - id: "grok_agent"
    backend:
      # No type specified - should infer "grok" from model
      model: "grok-3-mini"
      enable_web_search: false
    system_message: "You are a Grok assistant."

ui:
  display_type: "rich_terminal"
  logging_enabled: true