# ZAI Coding Team - Four Agents (glm-4.5 / glm-4.5-air)

agents:
  - id: "zai_glm45_agent_1"
    backend:
      type: "zai"
      model: "glm-4.5"
      base_url: "https://api.z.ai/api/paas/v4/"

  - id: "gemini2.5flash"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true

  - id: "claude-3-5-haiku"
    backend:
      type: "claude"
      model: "claude-3-5-haiku-20241022"
      enable_web_search: true
      enable_code_execution: true


ui:
  display_type: "rich_terminal"
  logging_enabled: true

