agents:
  - id: "architecture_glm45"
    backend:
      type: "zai"
      model: "glm-4.5"
      base_url: "https://api.z.ai/api/paas/v4/"
      temperature: 0.95
      top_p: 0.7
    system_message: |
      You are the best developer in the world

  - id: "claude_code_agent"
    backend:
      type: "claude_code"
      cwd: "claude_code_workspace" 

  - id: "gemini-2.5-flash"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true
      enable_code_execution: true

  # - id: "gpt-5"
  #   backend:
  #     type: "openai"
  #     model: "gpt-5"
  #     text: 
  #       verbosity: "medium"
  #     reasoning:
  #       effort: "high"
  #       summary: "auto"
  #     enable_web_search: true
  #     enable_code_interpreter: true

ui:
  display_type: "rich_terminal"
  logging_enabled: true

