# MassGen v3 Single Agent Configuration
# Simple configuration for single agent operation

agent:
  id: "assistant"
  backend:
    type: "grok"
    model: "grok-3-mini"
    enable_web_search: true
    return_citations: true

ui:
  display_type: "rich_terminal"  # Options: terminal, simple
  logging_enabled: true
