name: "Claude Single Agent"
description: "Single Claude agent for general queries with optional tools"

agents:
  - id: "claude_assistant"
    name: "Claude Assistant"
    system_message: "You are Claude, a helpful, harmless, and honest AI assistant created by Anthropic. You provide thoughtful, nuanced responses while being direct and concise when appropriate."
    backend:
      type: "claude"
      model: "claude-3-5-haiku-latest"
      enable_web_search: true
      enable_code_execution: true
