# MassGen v3 Three Agent Configuration
# Claude Haiku, GPT-4o-mini, and Grok-3-mini with builtin tools enabled

agents:
  - id: "4o"
    backend:
      type: "openai"
      model: "gpt-4o"
      enable_web_search: true
      enable_code_execution: true
    system_message: "You are a helpful AI assistant with web search and code execution capabilities."

  - id: "4omini"
    backend:
      type: "openai"
      model: "gpt-4o-mini"
      enable_web_search: true
      enable_code_interpreter: true
    system_message: "You are a helpful AI assistant with web search and code execution capabilities."

  - id: "grok3mini"
    backend:
      type: "grok"
      model: "grok-3-mini"
      enable_web_search: true
      return_citations: true
    system_message: "You are a helpful AI assistant with web search capabilities."

ui:
  display_type: "rich_terminal"
  logging_enabled: true