# MassGen v3 Three Agent Configuration
# Simple three-agent setup for focused collaboration

agents:
  - id: "search_agent"
    backend:
      type: "openai"
      model: "gpt-4o-mini"
      enable_web_search: true

  - id: "code_agent"
    backend:
      type: "openai"
      model: "gpt-4o-mini"
      enable_code_interpreter: true

  - id: "assistant"
    backend:
      type: "openai"
      model: "gpt-4o-mini"

ui:
  display_type: "rich_terminal"
  logging_enabled: true
