# MassGen v3 Three Agent Configuration
# Claude Haiku, GPT-4o-mini, and Grok-3-mini with builtin tools enabled

agents:
  - id: "claude_agent"
    backend:
      # type: "claude"
      # model: "claude-3-5-haiku-latest"
      type: "openai"
      model: "gpt-4o"
      enable_web_search: true
      enable_code_execution: true
    # system_message: "You are a helpful AI assistant with web search and code execution capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

  - id: "openai_agent"
    backend:
      type: "openai"
      model: "gpt-4o"
      enable_web_search: true
      enable_code_interpreter: true
    # system_message: "You are a helpful AI assistant with web search and code execution capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

  - id: "grok_agent"
    backend:
      # type: "grok"
      # model: "grok-3-mini"
      type: "openai"
      model: "gpt-4o"
      enable_web_search: true
      return_citations: true
    # system_message: "You are a helpful AI assistant with web search capabilities. For any question involving current events, recent information, or real-time data, ALWAYS use web search first."

ui:
  display_type: "rich_terminal"
  logging_enabled: true