# MassGen v3 Two Agent Configuration
# Simple two-agent setup for focused collaboration

agents:
  - id: "search_agent"
    backend:
      type: "openai"
      model: "gpt-4o-mini"
      enable_web_search: true

  - id: "code_agent"
    backend:
      type: "openai"
      model: "gpt-4o-mini"
      enable_code_interpreter: true

ui:
  display_type: "rich_terminal"
  logging_enabled: true

# Simple two-agent settings