agents:
- backend:
    model: gpt-4o-mini
    type: openai
  id: researcher
  system_message: You are a thorough researcher focused on gathering accurate information.
- backend:
    model: grok-3-mini
    type: grok
  id: analyst
  system_message: You are a critical analyst focused on evaluation and insights.
ui:
  display_type: terminal
  logging_enabled: true
